import React from "react";

let Keypad = (props) =>{
    return(
        <table>
            <tbody>
            <tr>
                <td>
                <button 
                    onClick={(e)=>{
                        props.displayOnScreen(e.target.innerText);
                    }}
                >(</button>
                </td>
                <td>
                <button
                    onClick={(e)=>{
                        props.displayOnScreen(e.target.innerText);
                    }}
                >)</button>
                </td>
                <td><button
                    onClick={()=>{
                        props.handleAllClear()
                    }}
                >AC</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >/</button></td>

            </tr>
            <tr>
                <td><button 
                onClick={(e)=>{
                    props.displayOnScreen(e.target.innerText);
                }}
                >7</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >8</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >9</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >*</button></td>
            </tr>
            <tr>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >4</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >5</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >6</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >+</button></td>
            </tr>
            <tr>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >1</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >2</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >3</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >-</button></td>
            </tr>

            <tr>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >.</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >0</button></td>
                <td>
                    <button
                        onClick={(e)=>{
                            props.displayOnScreen(e.target.innerText);
                        }}
                    >00</button></td>
                <td>
                    <button
                        onClick={()=>{
                            props.calculateValue()
                        }}
                    >=</button></td>
            </tr>
        </tbody>

        </table>
    )
}

export default Keypad;